apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    tier: backend
    app.kubernetes.io/name: nginx-pod
  # type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080