apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: haproxy-cluster-role-devops
rules:
- apiGroups: [""]
  resources: ["pods","services","Configmaps",”secrets”,"endpoints","nodes","namespaces","events","serviceaccounts"]
  verbs: ["get", "watch", "list", "create", "patch", "update"]