apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    app: db-pod
    target: front-end
spec:
  containers:
  - name: db-pod-container
    image: mysql:5.7
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    envFrom:
      - secretRef:
          name: db-secret
