apiVersion: v1
kind: Pod
metadata:
  name: yellow
  labels:
    app: yellow
spec:
  containers:
  - name: lemon
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  initContainers:
  - name: gold
    image: redis
    command: ['sh', '-c', "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
