apiVersion: v1
kind: Service
metadata:
  name: new-webapp-service
spec:
  selector:
    app: web-app
  type: NodePort
  #the Load balancer is used to expose the pod to internet
  #type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30081
  