apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
        tier: front-end
    spec:
      containers:
      - name: web-app-container
        image: nginx:alpine
        resources:
          limits:
            memory: "500Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80
