apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    tier: backend
    app.kubernetes.io/app: nginx-pod
    # labels: nginx-pod
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090 
      nodePort: 30082
