apiVersion: v1
kind: Pod
metadata:
  name: red
  labels:
    app: red
spec:
  containers:
  - name: redis-container
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  initContainers:
  - name: busy-box-container
    image: busybox
    command: ['sh', '-c', 'sleep 20']
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"