apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    name: test-pod
    tier: backend
spec:
  containers:
  - name: test-pod-container
    image: nginx:alpine
    resources:
      requests:
        memory: "1G"
        cpu: "0.5" 
      limits:
        memory: "2G"
        cpu: "1.0"
    ports:
     - containerPort: 6060