apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    tier: front-end
    app.kubernetes.io/name: web-app
  ports:
    - protocol: TCP
      port: 80 
      nodePort: 30082
