apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
    name: web-app
    tier: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
        name: web-app
    spec:
      containers:
      - name: web-app-container
        image: nginx
        resources:
          requests:
            memory: "1G"
            cpu: "0.5" 
          limits:
            memory: "2G"
            cpu: "1.0"
        ports:
        - containerPort: 80